Fix/layout style
naimuddin374/ecommerce-playground pull request #23
Opened 2022-12-04 14:13 UTC by SohagHossain9983

modify home page , card page checkout page

2022-12-04 14:22 UTC, rahmanshifur approved these changes
Good job

2022-12-04 14:53 UTC, naimuddin374 commented on components/layout/header/index.jsx
> +        <div className="sticky-top">
fix coding issue

2022-12-04 14:54 UTC, naimuddin374 commented on components/layout/header/top-navbar/header-action.jsx
> +
fix component name

2022-12-04 14:59 UTC, naimuddin374 commented on styles/components/layout/bottom-navbar/index.scss
> +
fix file name should be _ before

2022-12-04 14:59 UTC, naimuddin374 commented on styles/components/layout/bottom-navbar/modal-manu-item.scss
> +
fix file name

2022-12-04 15:00 UTC, naimuddin374 commented on styles/components/order-summary/index.scss
>  #OrderSummary{
fix filename

2022-12-04 15:00 UTC, naimuddin374 commented on styles/components/slider/index.scss
>          background: white;
fix filename

2022-12-04 15:01 UTC, naimuddin374 requested changes
follow the feedback

2022-12-07 12:42 UTC, naimuddin374 approved these changes

2022-12-07 12:43 UTC, naimuddin374 approved these changes

2022-12-07 12:55 UTC, naimuddin374 approved these changes

2022-12-07 12:55 UTC, merged