Component name fixing, createproduct-card and modifide some file,style
naimuddin374/ecommerce-playground pull request #24
Opened 2022-12-04 14:13 UTC by rahmanshifur

2022-12-04 14:23 UTC, SohagHossain9983 approved these changes
very good

2022-12-04 15:02 UTC, naimuddin374 commented on components/breadcrumb/index.jsx
> +                    <a href="#">{props.mainLink}</a>
add linktag

2022-12-04 15:03 UTC, naimuddin374 commented on components/filter-bar/filter-checkbox.jsx
> +                <Label for={props.CheckId} role="button" className="ms-2 mb-0">{props.name}</Label>
replace for to htmlFor

2022-12-04 15:05 UTC, naimuddin374 commented on components/pagination/pagination-number.jsx
> +const NumberPagination = () => {
fix component

2022-12-04 15:06 UTC, naimuddin374 commented on components/pagination/prev-button.jsx
> +        <div className="priv"><a className="px-2" href="#">Priv</a></div>
Use link instead of a tag

2022-12-04 15:13 UTC, naimuddin374 commented on styles/components/pagination/index.scss
>      .pagination-body {
change file name

2022-12-04 15:14 UTC, naimuddin374 commented on styles/components/shop-bar/index.scss
> + #shop-bar {
change filename

2022-12-04 15:14 UTC, naimuddin374 requested changes
change

2022-12-07 12:44 UTC, naimuddin374 approved these changes

2022-12-07 12:44 UTC, merged